stages:

  Data_Ingestion:
    cmd: python Respire\Pipeline\Data_Ingestion.py
    deps:
      - Respire\Pipeline\Data_Ingestion.py
      - Respire\Components\Data_Ingestion.py
      - Config\config.yaml
    outs:
      - Artifacts\Data_Ingestion\Chest-CT-Scan-data
    
  Base_Model:
    cmd: python Respire\Pipeline\Base_Model.py
    deps:
      - Respire\Pipeline\Base_Model.py
      - Respire\Components\Base_Model.py
      - Config\config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - Artifacts\Base_Model

  
  Model_Training:
    cmd: python Respire\Pipeline\Model_Trainer.py
    deps:
      - Respire\Pipeline\Model_Trainer.py
      - config\config.yaml
      - Artifacts\Data_Ingestion\Chest-CT-Scan-data
      - Artifacts\Base_Model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - Artifacts\Model_Training\Trained_Model.h5


  Model_Evaluation:
    cmd: python Respire\Pipeline\Model_Evaluation.py
    deps:
      - Respire\Pipeline\Model_Evaluation.py
      - config\config.yaml
      - Artifacts\Data_Ingestion\Chest-CT-Scan-data
      - Artifacts\Model_Training\Trained_model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false